# Generated by Django 3.1.4 on 2020-12-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Person',
        ),
    ]
